# Generated by Django 2.0 on 2018-01-01 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
            CREATE TRIGGER article_update_trigger
            BEFORE INSERT OR UPDATE OF headline, content, search_vector
            ON fts_article
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
              search_vector, 'pg_catalog.english', headline, content);

            UPDATE fts_article SET search_vector = NULL;
            ''',

            reverse_sql='''
            DROP TRIGGER IF EXISTS article_update_trigger
            ON fts_article;
            '''),
    ]
