# Generated by Django 2.0 on 2018-01-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fts', '0002_create_trigger'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
            DROP TRIGGER article_update_trigger ON fts_article;

            CREATE OR REPLACE FUNCTION update_article_search_vector()
            RETURNS TRIGGER
            LANGUAGE plpgsql AS $$
            BEGIN
              SELECT
                setweight(to_tsvector(
                  coalesce(NEW.headline, '')), 'A') ||
                setweight(to_tsvector(
                  coalesce(NEW.content, '')), 'B')
              INTO NEW.search_vector;
              RETURN NEW;
            END;
            $$;

            CREATE TRIGGER article_update_trigger
            BEFORE INSERT OR UPDATE OF headline, content, search_vector
            ON fts_article
            FOR EACH ROW EXECUTE PROCEDURE update_article_search_vector();

            UPDATE fts_article SET search_vector = NULL;
            ''',
            reverse_sql='''
            DROP TRIGGER article_update_trigger ON fts_article;

            DROP FUNCTION update_article_search_vector();

            CREATE TRIGGER article_update_trigger
            BEFORE INSERT OR UPDATE OF headline, content, search_vector
            ON fts_article
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
              search_vector, 'pg_catalog.english', headline, content);

            UPDATE fts_article SET search_vector = NULL;
            '''),
    ]
